# Generated by Django 2.1.1 on 2018-12-27 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(max_length=50)),
                ('Points', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Question',
            new_name='questions',
        ),
        migrations.AddField(
            model_name='solution',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizes.Question'),
        ),
    ]
