# Generated by Django 2.1.1 on 2018-12-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizes', '0002_auto_20181227_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='Points',
            field=models.FloatField(),
        ),
    ]
